src/Entity/Poster.php
<?php

namespace App\Entity;

use Symfony\Component\Serializer\Annotation\Groups;
use App\Repository\PosterRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PosterRepository::class)]
class Poster
{
#[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    #[Groups(['command'])]
    private ?int $id = null;

    #[ORM\Column]
    #[Groups(['command'])]
    private ?int $quantity = null;

    #[ORM\Column(length: 255)]
    #[Groups(['command'])]
    private ?string $artist = null;

    #[ORM\Column(length: 255)]
    #[Groups(['command'])]
    private ?string $album = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $added_at = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $updated_at = null;

     #[ORM\Column(length: 255)]
    private ?string $posterFile = null;

    
   
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getQuantity(): ?int
    {
        return $this->quantity;
    }

    public function setQuantity(int $quantity): static
    {
        $this->quantity = $quantity;

        return $this;
    }

    
    public function getArtist(): ?string
    {
    return $this->artist;
    }

    public function setArtist(string $artist): static
    {
        $this->artist = $artist;

        return $this;
    }

   
    public function getAlbum(): ?string
    {
        return $this->album;
    }

    public function setAlbum(string $album): static
    {
        $this->album = $album;

        return $this;
    }

    public function getAddedAt(): ?\DateTimeImmutable
    {
        return $this->added_at;
    }

    public function setAddedAt(\DateTimeImmutable $added_at): static
    {
        $this->added_at = $added_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeImmutable $updated_at): static
    {
        $this->updated_at = $updated_at;

        return $this;
    }

     public function getPosterFile(): ?string
    {
        return $this->posterFile;
    }

    public function setPosterFile(string $posterFile): static
    {
        $this->posterFile = $posterFile;

        return $this;
    }
    
public function __toString(): string
{
    return ($this->posterFile ?? 'no file') . ', ' . ($this->album ?? 'no album') . ', ' . ($this->artist ?? 'no artist');
}

}

src/Form/PosterType.php
<?php

namespace App\Form;

use App\Entity\Poster;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PosterType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('quantity')
            ->add('artist')
            ->add('album')
            ->add('added_at')
            ->add('updated_at')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Poster::class,
        ]);
    }
}

src/Controller/PosterController.php
<?php

namespace App\Controller;

use App\Entity\Poster;
use App\Form\PosterType;
use App\Repository\PosterRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Contracts\HttpClient\HttpClientInterface;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\Serializer\SerializerInterface;

#[Route('/poster')]
class PosterController extends AbstractController
{
    private $logger;

    public function __construct(LoggerInterface $logger)
    {
        $this->logger = $logger;
    }

    #[Route('/posters', name: 'app_poster_index', methods: ['GET'])]
    public function index(PosterRepository $posterRepository, SerializerInterface $serializer): Response
    {
        try {
            $data = $posterRepository->findAll();
            $response = $serializer->serialize($data, 'json');
            return new JsonResponse($response, 200, [], true);
        } catch (\Exception $e) {
            return new JsonResponse(['error' => $e->getMessage()], Response::HTTP_INTERNAL_SERVER_ERROR);
        }
    }

    #[Route('/new', name: 'app_poster_new', methods: ['POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        try {
            $poster = new Poster();
            $data = json_decode($request->getContent(), true);
            $poster->setArtist($data['artist']);
            $poster->setAlbum($data['album']);
            $poster->setQuantity($data['quantity']);
            $poster->setAddedAt(new \DateTimeImmutable());
            $poster->setUpdatedAt(new \DateTimeImmutable());
            $poster->setPosterFile($data['posterFile']);
            $entityManager->persist($poster);
            $entityManager->flush();
            return new JsonResponse(['status' => 'Poster created'], Response::HTTP_CREATED);
        } catch (\Exception $e) {
            return new JsonResponse(['error' => $e->getMessage()], Response::HTTP_INTERNAL_SERVER_ERROR);
        }
    }

    #[Route('/{id}', name: 'app_poster_show', methods: ['GET'])]
    public function show($id, PosterRepository $posterRepository, SerializerInterface $serializer): Response
    {
        try {
            $poster = $posterRepository->find($id);
            if ($poster === null) {
                throw new \Exception('Poster not found');
            }
            $response = $serializer->serialize($poster, 'json');
            return new JsonResponse($response, 200, [], true);
        } catch (\Exception $e) {
            return new JsonResponse(['error' => $e->getMessage()], Response::HTTP_INTERNAL_SERVER_ERROR);
        }
    }

    #[Route('/{id}/edit', name: 'app_poster_edit', methods: ['PUT'])]
    public function edit(Request $request, Poster $poster, EntityManagerInterface $entityManager): Response
    {
        try {
            $data = json_decode($request->getContent(), true);
            $poster->setArtist($data['artist']);
            $poster->setAlbum($data['album']);
            $poster->setQuantity($data['quantity']);
            $poster->setUpdatedAt(new \DateTimeImmutable());
            $poster->setPosterFile($data['posterFile']);
            $entityManager->flush();
            return new JsonResponse(['status' => 'Poster updated'], Response::HTTP_OK);
        } catch (\Exception $e) {
            return new JsonResponse(['error' => $e->getMessage()], Response::HTTP_INTERNAL_SERVER_ERROR);
        }
    }

    #[Route('/{id}', name: 'app_poster_delete', methods: ['DELETE'])]
    public function delete($id, PosterRepository $posterRepository, EntityManagerInterface $entityManager): Response
    {
        try {
            $poster = $posterRepository->find($id);
            if ($poster === null) {
                throw new \Exception('Poster not found');
            }
            $entityManager->remove($poster);
            $entityManager->flush();
            return new JsonResponse(['status' => 'Poster deleted'], Response::HTTP_NO_CONTENT);
        } catch (\Exception $e) {
            return new JsonResponse(['error' => $e->getMessage()], Response::HTTP_INTERNAL_SERVER_ERROR);
        }
    }

    #[Route('', name: 'app_poster_get_by_artist', methods: ['GET'])]
    public function getPosterByartist(Request $request, posterRepository $PosterRepository, SerializerInterface $serializer): Response
    {
        try {
            $artist = $request->query->get('artist');
            
            if (!$artist) {
                return new JsonResponse(['message' => 'artist parameter is missing'], Response::HTTP_BAD_REQUEST);
            }

            $artist = $PosterRepository->findByartist($artist);

            if ($artist === null) {
                return new JsonResponse(['message' => 'poster not found'], Response::HTTP_NOT_FOUND);
            }

            $response = $serializer->serialize($artist, 'json');
            return new JsonResponse($response, Response::HTTP_OK, [], true);
        } catch (\Exception $e) {
            return new JsonResponse(['error' => $e->getMessage()], Response::HTTP_INTERNAL_SERVER_ERROR);
        }
    }
    
}

templates/poster/_delete_form.html.twig
<form method="post" action="{{ path('app_poster_delete', {'id': poster.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ poster.id) }}">
    <button class="btn">Delete</button>
</form>

templates/poster/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Poster{% endblock %}

{% block body %}
    <h1>Edit Poster</h1>

    {{ include('poster/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_poster_index') }}">back to list</a>

    {{ include('poster/_delete_form.html.twig') }}
{% endblock %}

templates/poster/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Poster index{% endblock %}

{% block body %}
    <h1>Poster index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Quantity</th>
                <th>Artist</th>
                <th>Album</th>
                <th>Added_at</th>
                <th>Updated_at</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for poster in posters %}
            <tr>
                <td>{{ poster.id }}</td>
                <td>{{ poster.quantity }}</td>
                <td>{{ poster.artist }}</td>
                <td>{{ poster.album }}</td>
                <td>{{ poster.addedAt ? poster.addedAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ poster.updatedAt ? poster.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('app_poster_show', {'id': poster.id}) }}">show</a>
                    <a href="{{ path('app_poster_edit', {'id': poster.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_poster_new') }}">Create new</a>
{% endblock %}

templates/poster/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Poster{% endblock %}

{% block body %}
    <h1>Create new Poster</h1>

    {{ include('poster/_form.html.twig') }}

    <a href="{{ path('app_poster_index') }}">back to list</a>
{% endblock %}

templates/poster/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Poster{% endblock %}

{% block body %}
    <h1>Poster</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ poster.id }}</td>
            </tr>
            <tr>
                <th>Quantity</th>
                <td>{{ poster.quantity }}</td>
            </tr>
            <tr>
                <th>Artist</th>
                <td>{{ poster.artist }}</td>
            </tr>
            <tr>
                <th>Album</th>
                <td>{{ poster.album }}</td>
            </tr>
            <tr>
                <th>Added_at</th>
                <td>{{ poster.addedAt ? poster.addedAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Updated_at</th>
                <td>{{ poster.updatedAt ? poster.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_poster_index') }}">back to list</a>

    <a href="{{ path('app_poster_edit', {'id': poster.id}) }}">edit</a>

    {{ include('poster/_delete_form.html.twig') }}
{% endblock %}